# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 512df955deb86c40b24dd6e312efd0b7142487cb93703ecb9b748ef992e62afad0f98bd8d93e3bacb27c83a3b2e414bd3114f23aa99297c739e07e45eb9ba8d5

test:
  secret_key_base: 9b20b3e390609150d2ef6391e01567d411f72534364b0f87e904bf9c821fcf4358b4672c815f5a561379d7fdd88382e5f4a43b8e63ee9e0c27ad46280d26199a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
